#!/usr/bin/env python3
"""Generate the paper's figures from table/tu102_ops.csv.

Committed artefacts regenerated by `make figures`; PDF for the LaTeX build,
SVG for the PAPER.md mirror. Style matches the paper: one accent colour for
measured series, grey for models and reference lines, no chartjunk.
"""

import csv
import os

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "paper", "figures")

ACCENT = "#1F5F5B"
GREY = "#888888"

plt.rcParams.update({
    "font.family": "serif",
    "font.serif": ["TeX Gyre Pagella", "P052", "Palatino", "DejaVu Serif"],
    "font.size": 8.5,
    "axes.spines.top": False,
    "axes.spines.right": False,
    "axes.linewidth": 0.6,
    "xtick.major.width": 0.6,
    "ytick.major.width": 0.6,
    "lines.linewidth": 1.2,
    "lines.markersize": 3.5,
    "svg.fonttype": "none",
})


def load():
    rows = {}
    with open(os.path.join(ROOT, "table", "tu102_ops.csv")) as f:
        for r in csv.DictReader(f):
            rows[(r["row_id"], r["variant"])] = r
    return rows


def v(rows, rid, variant):
    return float(rows[(rid, variant)]["value"])


def save(fig, name):
    for ext in ("pdf", "svg"):
        fig.savefig(os.path.join(OUT, f"{name}.{ext}"), bbox_inches="tight")
    plt.close(fig)
    print(name)


def fig_hierarchy(rows):
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(6.3, 2.4))

    fp = [8, 32, 64, 128, 1024, 5120, 8192, 32768]
    lat = [v(rows, "mem.pchase.lat", f"fp{k}k") for k in fp]
    ax1.semilogx(fp, lat, "o-", color=ACCENT)
    ax1.set_xlabel("footprint (KiB)")
    ax1.set_ylabel("load latency (ns)")
    ax1.annotate("L1", (16, lat[0]), textcoords="offset points",
                 xytext=(-3, 8), ha="center")
    ax1.annotate("L2", (800, lat[4]), textcoords="offset points",
                 xytext=(0, 8), ha="center")
    ax1.annotate("DRAM", (16384, lat[7]), textcoords="offset points",
                 xytext=(0, 8), ha="center")
    ax1.set_ylim(0, 340)

    reach = [16, 32, 64, 128, 256, 512, 1024, 2048, 4096, 8192, 12288, 16384]
    tlat = [v(rows, "mem.tlb.lat", f"reach{k}m") for k in reach]
    ax2.semilogx(reach, tlat, "o-", color=ACCENT)
    ax2.set_xlabel("pointer-chase reach (MiB)")
    ax2.set_ylabel("L2-resident latency (ns)")
    ax2.annotate("L1 TLB miss  +7 ns", (64, tlat[2]), textcoords="offset points",
                 xytext=(4, -14))
    ax2.annotate("L2 TLB miss  +6 ns", (12288, tlat[10]),
                 textcoords="offset points", xytext=(-8, -3), ha="right")
    ax2.set_ylim(155, 178)

    fig.tight_layout(w_pad=2.0)
    save(fig, "fig_hierarchy")


def fig_laws(rows):
    fig, ax = plt.subplots(figsize=(4.4, 2.6))
    ways = [1, 2, 4, 8, 16, 32]
    smem = [v(rows, "mem.smem.lat", f"conflict{w}") for w in ways]
    warps = [1, 2, 4, 6, 8, 16, 32]
    bar = [v(rows, "sync.bar.lat", f"w{w}") for w in warps]

    xs = list(range(1, 33))
    ax.plot(xs, [22 + 2 * (x - 1) for x in xs], "--", color=GREY, lw=0.9,
            label=None, zorder=1)
    ax.plot(warps, bar, "s", ms=6.0, mfc="white", mec=ACCENT, mew=1.0,
            label="BAR.SYNC (warps in block)")
    ax.plot(ways, smem, "o", ms=2.8, color=ACCENT,
            label="shared-memory conflict (ways)")
    ax.set_xscale("log", base=2)
    ax.set_xticks(ways)
    ax.set_xticklabels([str(w) for w in ways])
    ax.set_xlabel("degree (conflict ways / warps)")
    ax.set_ylabel("latency (cycles)")
    ax.annotate("22 + 2(n−1)", (12, 22 + 2 * 11), textcoords="offset points",
                xytext=(12, -16), color=GREY)
    ax.legend(frameon=False, loc="upper left", fontsize=8)
    save(fig, "fig_laws")


def fig_stride(rows):
    fig, ax = plt.subplots(figsize=(4.4, 2.6))
    strides = [1, 4, 18, 32, 128]
    useful = [v(rows, "mem.ldg.u8.stride.tput", f"stride{s}") for s in strides]
    fetched = [u * min(s, 32) for u, s in zip(useful, strides)]
    dram = v(rows, "mem.dram.bw", "read")

    xpos = range(len(strides))
    ax.bar([x - 0.18 for x in xpos], useful, 0.36, color=ACCENT,
           label="useful bytes")
    # the formula lives in the caption; a long legend entry covers the bars
    ax.bar([x + 0.18 for x in xpos], fetched, 0.36, color=GREY, alpha=0.55,
           label="fetched traffic")
    ax.axhline(dram, ls="--", color=GREY, lw=0.9)
    ax.annotate(f"DRAM read  {dram:.0f} GB/s", (len(strides) - 0.55, dram),
                textcoords="offset points", xytext=(0, 4), color=GREY,
                ha="right")
    ax.set_xticks(list(xpos))
    ax.set_xticklabels([str(s) for s in strides])
    ax.set_xlabel("load stride (bytes)")
    ax.set_ylabel("bandwidth (GB/s)")
    ax.annotate("request-\nbound", (0, useful[0]), textcoords="offset points",
                xytext=(-14, 6), fontsize=7.5)
    ax.annotate("TLB /\nactivation", (4 + 0.18, fetched[4]),
                textcoords="offset points", xytext=(-10, 6), fontsize=7.5)
    ax.legend(frameon=False, loc="upper left", bbox_to_anchor=(0.0, 0.92),
              fontsize=8)
    save(fig, "fig_stride")


def fig_exchange(rows):
    fig, ax = plt.subplots(figsize=(4.4, 2.6))
    payload = [0, 4, 20]
    rt = [(v(rows, "x.nvlink.fence_roundtrip", f"{b}b_gpu0to1")
           + v(rows, "x.nvlink.fence_roundtrip", f"{b}b_gpu1to0")) / 2
          for b in (0, 4096, 20480)]
    nsz = [4, 16, 20, 64]
    nccl = [v(rows, "x.nccl.allreduce", f"{b}b_steady")
            for b in (4096, 16384, 20480, 65536)]

    ax.plot(nsz, nccl, "s-", mfc="white", mec=GREY, color=GREY)
    ax.plot(nsz, [n / 2 for n in nccl], "--", color=GREY, lw=0.9)
    ax.plot(payload, rt, "o-", color=ACCENT)
    ax.annotate("NCCL all-reduce, steady", (64, nccl[-1]),
                textcoords="offset points", xytext=(-4, 8), ha="right",
                color=GREY)
    ax.annotate("half NCCL (the registered bar)", (64, nccl[-1] / 2),
                textcoords="offset points", xytext=(-4, 7), ha="right",
                color=GREY)
    ax.annotate("exchange round trip\n(store + fence + poll)", (20, rt[2]),
                textcoords="offset points", xytext=(10, -4), color=ACCENT)
    ax.annotate("2.2×", (4, rt[1]), textcoords="offset points",
                xytext=(2, -14), color=ACCENT)
    ax.annotate("1.6× under the bar", (20, rt[2]), textcoords="offset points",
                xytext=(2, -16), color=ACCENT)
    ax.set_xlabel("payload (KiB)")
    ax.set_ylabel("time (µs)")
    ax.set_xlim(-2, 66)
    ax.set_ylim(0, 31)
    save(fig, "fig_exchange")


def main():
    os.makedirs(OUT, exist_ok=True)
    rows = load()
    fig_hierarchy(rows)
    fig_laws(rows)
    fig_stride(rows)
    fig_exchange(rows)


if __name__ == "__main__":
    main()
