#!/usr/bin/env python3
"""Generate the paper's LaTeX tables from table/tu102_ops.csv.

Committed artefacts regenerated by `make tables`; derived from the published
table so the paper cannot drift from the data. Style: booktabs only, units
stated once, \\addlinespace between op families, no vertical rules.
"""

import csv
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "paper", "tables")

HEADER = "% generated by tools/mk_paper_tables.py -- do not edit\n"


def load():
    rows = {}
    with open(os.path.join(ROOT, "table", "tu102_ops.csv")) as f:
        for r in csv.DictReader(f):
            rows[(r["row_id"], r["variant"])] = r
    return rows


def val(rows, rid, variant="", nd=1):
    r = rows.get((rid, variant))
    if r is None or not r["value"]:
        raise KeyError(f"{rid}/{variant}")
    return f"{float(r['value']):.{nd}f}"


def prior(rows, rid, variant=""):
    r = rows.get((rid, variant))
    if r is None or not r["prior_value"]:
        return "--", "--"
    d = f"${float(r['deviation_pct']):+.1f}$" if r["deviation_pct"] else "--"
    return r["prior_value"], d


def pipe(rows, rid, variant=""):
    r = rows.get((rid, variant))
    p = (r or {}).get("pipe", "")
    return p if p else "--"


def core_table(rows):
    # groups of (SASS label, lat (rid, variant), tput (rid, variant))
    groups = [
        [("FFMA", ("alu.ffma.lat", ""), ("alu.ffma.tput", "w8")),
         ("FADD", ("alu.fadd.lat", ""), ("alu.fadd.tput", "w32")),
         ("FMUL", ("alu.fmul.lat", ""), ("alu.fmul.tput", "w32"))],
        [("IMAD", ("alu.imad.lat", ""), ("alu.imad.tput", "w8")),
         ("IADD3*", ("alu.iadd3.lat", "derived"), ("alu.iadd3.tput", "w32_mixpair")),
         ("LOP3", ("alu.lop3.lat", ""), ("alu.lop3.tput", "w8")),
         ("SHF", ("alu.shf.lat", ""), ("alu.shf.tput", "w8")),
         ("SEL", ("alu.sel.lat", ""), ("alu.sel.tput", "w32")),
         ("PRMT", ("alu.prmt.lat", ""), ("alu.prmt.tput", "w32")),
         ("ISETP*", ("alu.isetp.lat", "derived"), ("alu.isetp.tput", "w32_pair")),
         ("IDP.4A.S8", ("alu.idp4a.lat", "s8"), ("alu.idp4a.tput", "w8_s8"))],
        [("HFMA2", ("alu.hfma2.lat", ""), ("alu.hfma2.tput", "w32")),
         ("DADD", ("alu.dadd.lat", ""), ("alu.dadd.tput", "w32")),
         ("DFMA", ("alu.dfma.lat", ""), ("alu.dfma.tput", "w32"))],
        [("POPC", ("alu.popc.lat", ""), ("alu.popc.tput", "w16")),
         ("FLO", ("alu.flo.lat", ""), ("alu.flo.tput", "w16"))],
        [("MUFU.EX2", ("sfu.mufu.ex2.lat", ""), ("sfu.mufu.ex2.tput", "w32")),
         ("MUFU.RSQ", ("sfu.mufu.rsq.lat", ""), ("sfu.mufu.rsq.tput", "w16")),
         ("MUFU.SIN", ("sfu.mufu.sin.lat", ""), ("sfu.mufu.sin.tput", "w16"))],
        [("SHFL.IDX", ("sync.shfl.lat", "idx"), ("sync.shfl.tput", "w4_idx"))],
    ]
    lines = [HEADER + "\\begin{tabular}{@{}l l r r r r@{}}",
             "\\toprule",
             " & & \\multicolumn{3}{c}{latency (cycles)} & throughput \\\\",
             "\\cmidrule(lr){3-5}",
             "op & pipe & meas. & prior & dev.\\,\\% & (wi/SM/clk) \\\\",
             "\\midrule"]
    for gi, group in enumerate(groups):
        if gi:
            lines.append("\\addlinespace")
        for label, lk, tk in group:
            p, d = prior(rows, *lk)
            lines.append(
                f"\\texttt{{{label}}} & {pipe(rows, *lk)} & {val(rows, *lk, nd=1)}"
                f" & {p} & {d} & {val(rows, *tk, nd=2)} \\\\")
    lines += ["\\bottomrule", "\\end{tabular}"]
    return "\n".join(lines) + "\n"


def tensor_table(rows):
    spec = [
        ("\\texttt{HMMA.1688}, f16 accumulate", ("tensor.hmma.1688.tput", "w8_f16acc")),
        ("\\texttt{HMMA.1688}, f32 accumulate", ("tensor.hmma.1688.tput", "w8_f32acc")),
        ("\\texttt{IMMA.8816}, s8", ("tensor.imma.8816.tput", "w8_s8")),
    ]
    lines = [HEADER + "\\begin{tabular}{@{}l r r r@{}}",
             "\\toprule",
             "op & tput (wi/SM/clk) & prior & dev.\\,\\% \\\\",
             "\\midrule"]
    for label, k in spec:
        p, d = prior(rows, *k)
        lines.append(f"{label} & {val(rows, *k, nd=3)} & {p} & {d} \\\\")
    lines.append("\\addlinespace")
    lines.append(f"\\texttt{{HMMA.1688}} dependent latency & "
                 f"\\multicolumn{{3}}{{r}}{{{val(rows, 'tensor.hmma.1688.lat', 'd_feeds_a', nd=1)} cycles}} \\\\")
    lines += ["\\bottomrule", "\\end{tabular}"]
    return "\n".join(lines) + "\n"


def memory_table(rows):
    spec = [
        ("shared memory (no conflict)",
         val(rows, "mem.smem.lat", "conflict1", nd=0) + " cyc",
         val(rows, "mem.smem.bw", "w8_f32", nd=1) + " B/clk/SM"),
        ("L1 data, hit (= \\texttt{\\_\\_ldg} path)",
         val(rows, "mem.l1.lat", "l1hit", nd=0) + " cyc",
         val(rows, "mem.l1.bw", "w16_f32", nd=1) + " B/clk/SM"),
        ("constant, cbank hit",
         val(rows, "mem.const.cbank.lat", "", nd=1) + " cyc", "--"),
        ("constant, uniform path (\\texttt{ULDC})",
         val(rows, "mem.const.uldc.lat", "", nd=1) + " cyc", "--"),
        ("L2, hit (\\texttt{.cg} service)",
         val(rows, "mem.l2.lat", "fp4096k", nd=0) + " ns",
         val(rows, "mem.l2.bw", "read_cg", nd=1) + " GB/s"),
        ("L2 aggregate via L1 (default policy)", "--",
         val(rows, "mem.l2.bw", "read_default", nd=0) + " GB/s"),
        ("DRAM (read / write / copy)",
         val(rows, "mem.dram.lat", "fp262144k", nd=0) + " ns",
         " / ".join(val(rows, "mem.dram.bw", v, nd=0)
                    for v in ("read", "write", "copy")) + " GB/s"),
    ]
    lines = [HEADER + "\\begin{tabular}{@{}l r r@{}}",
             "\\toprule",
             "level & latency & bandwidth \\\\",
             "\\midrule"]
    for label, lat, bw in spec:
        lines.append(f"{label} & {lat} & {bw} \\\\")
    lines += ["\\bottomrule", "\\end{tabular}"]
    return "\n".join(lines) + "\n"


def x_table(rows):
    def us(rid, variant, nd=2):
        return val(rows, rid, variant, nd=nd) + " \\textmu s"
    spec = [
        ("peer load latency (NVLink hop)",
         val(rows, "x.nvlink.peer_ldg.lat", "gpu0to1", nd=0) + " ns"),
        ("peer \\texttt{atomicAdd} latency",
         val(rows, "x.nvlink.peer_atom.add.lat", "gpu0to1", nd=0) + " ns"),
        ("peer read bandwidth",
         val(rows, "x.nvlink.peer_ldg.bw", "gpu0to1", nd=1) + " GB/s"),
        ("peer write bandwidth",
         val(rows, "x.nvlink.peer_stg.bw", "gpu0to1", nd=1) + " GB/s"),
        ("ADDLINESPACE", ""),
        ("one-way message, flag only", us("x.nvlink.msg.oneway", "0b_gpu0to1")),
        ("exchange round trip, flag only", us("x.nvlink.fence_roundtrip", "0b_gpu0to1")),
        ("exchange round trip, 4 KiB", us("x.nvlink.fence_roundtrip", "4096b_gpu0to1")),
        ("exchange round trip, 20 KiB", us("x.nvlink.fence_roundtrip", "20480b_gpu0to1")),
        ("ADDLINESPACE", ""),
        ("NCCL all-reduce, 4 KiB steady", us("x.nccl.allreduce", "4096b_steady", nd=1)),
        ("NCCL all-reduce, 20 KiB steady", us("x.nccl.allreduce", "20480b_steady", nd=1)),
        ("NCCL all-reduce, first call (cold)",
         f"{float(rows[('x.nccl.allreduce', '20480b_cold')]['value'])/1000:.2f} ms"),
        ("ADDLINESPACE", ""),
        ("PCIe 3.0 x16 pinned H2D / D2H",
         val(rows, "x.pcie.bw", "h2d_pinned_gpu0", nd=1) + " / "
         + val(rows, "x.pcie.bw", "d2h_pinned_gpu0", nd=1) + " GB/s"),
        ("PCIe small-transfer floor (4 B H2D)", us("x.pcie.lat", "h2d_4b_gpu0")),
    ]
    lines = [HEADER + "\\begin{tabular}{@{}l r@{}}",
             "\\toprule",
             "quantity & value \\\\",
             "\\midrule"]
    for label, v in spec:
        if label == "ADDLINESPACE":
            lines.append("\\addlinespace")
        else:
            lines.append(f"{label} & {v} \\\\")
    lines += ["\\bottomrule", "\\end{tabular}"]
    return "\n".join(lines) + "\n"


def main():
    os.makedirs(OUT, exist_ok=True)
    rows = load()
    for name, fn in [("tab_core.tex", core_table),
                     ("tab_tensor.tex", tensor_table),
                     ("tab_memory.tex", memory_table),
                     ("tab_interconnect.tex", x_table)]:
        with open(os.path.join(OUT, name), "w") as f:
            f.write(fn(rows))
        print(name)


if __name__ == "__main__":
    main()
